declare const styles: {
  readonly "album": string;
  readonly "albumBrowser": string;
  readonly "albumBrowserTitle": string;
  readonly "albumContainer": string;
  readonly "albumDescription": string;
  readonly "albumIcon": string;
  readonly "albumTitle": string;
  readonly "browser": string;
  readonly "controls": string;
  readonly "currentProgress": string;
  readonly "currentSong": string;
  readonly "currentSongAlbum": string;
  readonly "currentSongAlbumName": string;
  readonly "currentSongName": string;
  readonly "nowPlaying": string;
  readonly "playButton": string;
  readonly "player": string;
  readonly "progressMeter": string;
  readonly "song": string;
  readonly "songBrowser": string;
  readonly "songBrowserBack": string;
  readonly "songBrowserSongs": string;
  readonly "songBrowserTitle": string;
  readonly "songBrowserTitleBar": string;
  readonly "songContainer": string;
  readonly "songIndex": string;
  readonly "songName": string;
};
export = styles;

